### ISSUE TITLE
need props className

### ISSUE THREAD

**Issue by muh-hizbe** [harshzalavadiya/react-tag-input-component#1]
I hope react-tag-component have className props, with it we can customize tag input style like border-radius, border, ring on focus, and coloring them.

**Comment by harshzalavadiya** [comment]
@muh-hizbe I have added `rti--*` prefixed classes to tag input component you can directly target them since they are added just for that

**Comment by muh-hizbe** [comment]
@harshzalavadiya it's not flexible custom css. I will customize `outline` to be _none_ and apply a `ring` when it's focus.

**Comment by muh-hizbe** [comment]
#solved

i cannot change it when focus, because i use pseudo-classes `:focus`, but when i change it in to `:focus-within` it's work.
maybe you can put documentation for customize effect using pseudo-classes, i hope with it can helpfull anyone when they're will customize the component.
